version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install node packages
          command: |
             npm install
             npm run release
             ls
      - run:
          name: Clone Public domain
          working_directory: ~/workdir
          command: |
            pwd
            git clone --depth 1 https://${GITHUB_TOKEN}@github.com/damianpumar/damianpumar.github.io.git
      - run:
          name: Clean old files
          working_directory: ~/workdir/damianpumar.github.io
          command: |
            rm -rf *
      - run:
          name: Copy dist into workdir
          working_directory: ~/repo
          command: |
            cp -a dist/. ~/workdir/damianpumar.github.io
            ls ~/workdir/damianpumar.github.io
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/damianpumar.github.io
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "Deployment Bot"
            git add .
            git commit --allow-empty -m "Trigger deployment new Release"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/damianpumar/damianpumar.github.io.git master
