version: 2
jobs:
  build:
    docker:
      - image: cimg/node:26.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install node packages
          command: |
            git config --global url."https://".insteadOf git://
            npm install
            npm run build
      - run:
          name: Clone Public domain
          working_directory: ~/workdir
          command: |
            pwd
            git clone --depth 1 https://${GITHUB_TOKEN}@github.com/damianpumar/damianpumar.github.io.git
      - run:
          name: Clean old files
          working_directory: ~/workdir/damianpumar.github.io
          command: |
            mkdir ../tmp
            mv CNAME ../tmp
            rm -rf *
            mv ../tmp/* .
            rm -d ../tmp
      - run:
          name: Copy dist into workdir
          working_directory: ~/repo
          command: |
            cp -a dist/. ~/workdir/damianpumar.github.io
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/damianpumar.github.io
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "Deployment Bot"
            git add .
            git commit --allow-empty -m "🤖 Trigger deployment new Release"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/damianpumar/damianpumar.github.io.git master
