version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: gulp dist
      - run:
          name: Clone Public domain
          working_directory: ~/workdir
          command: |
            git clone --depth 1 https://${GITHUB_TOKEN}@github.com/damianpumar/damianpumar.github.io.git
      - run:
          name: Clean old files
          command: |
            rm -rf .
      - run:
          name: Pase dist into workdir
          command: |
            cp -a ~/repo/dist/. ~/workdir
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "Trigger deployment new Release"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/damianpumar/damianpumar.github.io.git master
