on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: "10.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install and release
        run: |
          npm install
          npm run release
      - name: FTP Deployment
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /home/runner/work/MyResume/MyResume/dist/
          server-dir: ${{ secrets.PATH_PROJECT }}
